name: Compile Sketch

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.yml"
      - "data/**"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.yml"
      - "data/**"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  schedule:
    # Run every Saturday at 6 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 6 * * SAT"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: adafruit:samd:adafruit_feather_m0
            platforms: |
              - name: "adafruit:samd"
                source-url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            - source-url: https://github.com/generationmake/DogGraphicDisplay
            - name: 107-Arduino-NMEA-Parser
            - name: Geek Factory TimeLib Library
            - name: Adafruit Si5351 Library
            - name: Etherkit JTEncode
          sketch-paths: |
            - ${{ github.workspace }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
